# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 957fcecb3cb73b2d2f16203d2fb369c8222bdff272556933be957e15aa0bb376eaa39aa8f81c88994315b11f0301b733b2bd4cbfd8cf5de6faec27f8c35bc548

test:
  secret_key_base: c508a725cedbc1334b5e787525804c8bbab19a94ed69ad009c9435c7d10062eb73b650ccb1988cd48ef6743f2226846fbb39f9894c927944a3e88bae492f305d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
